version: "3.8"
services:

  backend:
    build: .
    restart: always
    ports:
      - "4001:${PORT}"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ep-billowing-glade-a2a79qgv.eu-central-1.aws.neon.tech/postgresql?sslmode=require"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: petProjectBD
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

